<Project>
  <Import Project="../Directory.Build.props" />
  <PropertyGroup>
    <Authors>Ling</Authors>
    <PackageProjectUrl>https://github.com/ling921/ling-configuration-database</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ling921/ling-configuration-database</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>configuration;database;IConfiguration;reload;dotnet</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="$(SourceLinkVersion)" PrivateAssets="all" />
  </ItemGroup>
</Project>
