<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Ling.Configuration.Database.AdoNet</PackageId>
    <Title>Ling.Configuration.Database.AdoNet</Title>
    <Description>ADO.NET adapter for Ling.Configuration.Database.</Description>
    <RootNamespace>Ling.Configuration.Database.AdoNet</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ling.Configuration.Database/Ling.Configuration.Database.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="README.zh-CN.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
